project_id = "wkohhgehavsmtqyjtxcb"

[functions.search-licitacoes]
verify_jwt = false

[functions.create-checkout]
verify_jwt = false

[functions.check-subscription]
verify_jwt = false

[functions.customer-portal]
verify_jwt = false

[functions.promote-to-admin]
verify_jwt = false

[functions.list-users]
verify_jwt = false